controller_manager:
  ros__parameters:
    update_rate: 1000


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - camera_joint
      - front_right_joint1
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
